[workspace]
resolver = "2"
members = [
    "ansi-escape",
    "apply-patch",
    "cli",
    "core",
    "exec",
    "execpolicy",
    "repl",
    "tui",
]

[workspace.package]
version = "0.1.0"

[profile.release]
lto = "fat"